config/routes.rb
Rails.application.routes.draw do
  get 'images/index'

  resources :images
  
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'

  scope '/marigym' do
  	get 'welcome/index'
    resources :images
    root 'welcome#index'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	belongs_to :user
#	after_create :save_users 

	def self.search(search)
  		where("nombre || ubicacion || autor LIKE ?", "%#{search}%")
	end 

	#def users=(value)
	#	@users = value
		
	#end

	#def save_users
	#	@users.each do |user_id|
	#		HasCategory.create(user_id: user_id, image_id: self.id)
	#	end
	#end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	#GET 
	def index
  		@images = Image.all
  		if params[:search]
    		@images = Image.search(params[:search])
  		else
    		@images = Image.all.order('created_at DESC')
  		end
	end	

	#GET
	def show
		@image = Image.find(params[:id])
	end

	#GET
	def new
		@image = Image.new
		#
		#@users = User.all
	end

	#POST
	def create
		@image = current_user.images.new(image_params)
		#@image.users = params[:users]
		if @image.save
			redirect_to @image
		else
			render :new
		end	
	end

	#DELETE
	def destroy
		@image = Image.find(params[:id])
		@image.destroy
		redirect_to images_index_path 
	end

	def edit
		@image = Image.find(params[:id])
	end

	#UPDATE
	def update
		@image = Image.find(params[:id])
		if @image.update(image_params)
			redirect_to @image
		else
			render :edit
		end	
	end

	private

	def image_params
		params.require(:image).permit(:nombre,:ubicacion,:fecha,:autor, :peso, :users)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<h2><%= t('.contact_us') %></h2>
<%= simple_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
<% end %>

app/views/images/_form.html.erb
<div class="crearimagen">
<h1><%= name%> imagen</h1>
<br>
<%= form_for(@image) do |f|%>
	<% @image.errors.full_messages.each do |message|%>
		*<%= message %>
	<%end%>
	<div class="field ">
		<%= f.text_field :nombre, placeholder: "Nombre", autofocus: true, class:"campocrear" %>
	</div>
	<div class="field ">
		<%= f.text_field :ubicacion, placeholder: "Ubicacion", autofocus: true, class:"campocrear"%> 
	</div>
	<div class="field ">	
		<%= f.text_field :fecha, placeholder: "Fecha", autofocus: true, class:"campocrear"%> 
	</div>	
	<div class="field ">
		<%= f.text_field :autor, placeholder: "Autor", autofocus: true, class:"campocrear"%> 
	</div>	
	<div class="field">
		<%= f.text_field :peso, placeholder: "Compartir (Escriba si o no)", autofocus: true, class:"campocrear"%>
	</div>
	<br> 
	<%= f.submit "Guardar", class:"botonguardar"%>
<%end%>
</div>

app/views/images/edit.html.erb
<%= render "form", name: "Editar"%>

app/views/images/index.html.erb
<%= form_tag(images_path, :method => "get", id: "search-form") do %> 
<%= text_field_tag :search, params[:search], placeholder: "Buscar Imagen", class:"camposearch" %>
<%= submit_tag "Search", class:"botonsearch" %>
<% end %>
<% if user_signed_in? %>
	<h1 class="usuario"><%= current_user.email%></h1>
	<%= link_to "Agregar imagen", new_image_path, class:"agregarimagen"%>
	<div class="fotos">
	<div class="row">	
	<% @images.each do |image|%>
		<% if current_user.id ==  image.user_id || image.peso == 'si'%>
			<div class="col-sm-4 ancho">
			<h2><%= image.nombre%></h2>
			<p><%=  image.ubicacion%></p>
			<p><%=  image.autor%></p>
			<h3><%= link_to "ver", image_path(image) %> </h3>
			</div>	
		<% end %>
  	<%end%> 
  	<%else%>
  	<div class="fotos">
	<div class="row">
  	<% @images.each do |image|%>
  		<div class="col-sm-4 ancho">
  			<h2><%= image.nombre%></h2>
  		</div>	
  	<% end %>
  	</div>
  	</div>
<%end%>

app/views/images/new.html.erb
<%= render "form", name: "Crear"%>

app/views/images/show.html.erb
<% unless @image.user.nil? %>
	<h1 class="usuario"><%= @image.user.email%></h1>
<%end%>
<div class="showimagen">
	<h2><%= @image.nombre%></h2>
	<p><%=  @image.ubicacion%></p>
	<p><%=  @image.fecha%></p>
	<p><%=  @image.autor%></p>
	<p><%=  @image.peso%></p>
</div>
<div class="eliminareditar">
	<%= link_to "Eliminar", @image, method: :delete%>
	<%= link_to "Editar", edit_image_path() %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html> 
  <head>
    <title>Gym</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="navbar">
    <li>
      <%= link_to "Inicio", welcome_index_path%>
      <% if user_signed_in? %>
    </li>  
  	  <li>
      <li>
        <%= link_to "Mis imagenes", 
        images_index_path%>
      </li>
        <%= link_to "Cerrar sesión",  destroy_user_session_path , method: :delete %>
      </li>   
    <%else%>
      <li>
  		  <%= link_to "Iniciar sesión", new_user_session_path%>	
      </li>   
      <li>  
  		<%= link_to "Registrarse", new_user_registration_path%>
      </li> 
      <li>
      <%= link_to "Contenido publico", images_index_path%>
      </li>  
    <%end%>
  </div>

  <body>
    
    <%= yield %>
  </body>
</html>

app/views/welcome/_prueba.html.erb
<h2> bien </h2>

app/views/welcome/index.html.erb
<div class="fondoindex">
	<div class="page-header gym">
	<h1>GYM</h1>
  
    <blockquote>
        <p>Para ser el número uno, tienes que entrenar como si fueras el número dos.</p>
        <footer>Maurice Green.</footer>
    </blockquote>

</div>

</div>

app/views/welcome/prueba.html.erb
<h2> bien </h2>